name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: sfdx-actions/setup-sfdx@v1
      #   with:
      #     sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      # - name: sfdx-test-run
      #   run: sfdx force:apex:test:run -l RunLocalTests -w 30
    - name: display scratch org
      run: sfdx force:org:display
